#!/usr/bin/env bash

case $@ in
  "")
    SEARCH='tag:new'
    TITLE='New MAIL'
    ;;
  *)
    SEARCH=$@
    TITLE="MAIL ($@)"
    ;;
esac

OUT=""

for msg in `notmuch search --output=messages $SEARCH`;
do
  auths=`notmuch search --format=json --output=summary $msg |\
    sed -e 's/,/\n/g' | grep authors |\
    sed -e 's/.*:[ \t"]*//' -e 's/[ \t"]*$//'`
  subj=`notmuch search --format=json --output=summary $msg |\
    sed -e 's/,/\n/g' | grep subject |\
    sed -e 's/.*:[ \t"]*//' -e 's/[ \t"]*$//'`
  OUT="$OUT<b>${auths:0:15}:</b> ${subj:0:20}\n"
done

# check if there is some output
if [[ ${OUT} != "" ]];
then
  notify-send -u normal "$TITLE" "$OUT"
fi
