#!/bin/sh


# Check if connected
is_connected
STATE=$?

if [ $STATE -eq 0 ]
then
    echo "No internet connection."
else
    # ensure gpg-agent is running
    # echo RELOADAGENT | gpg-connect-agent >> /dev/null
    gpg-connect-agent /bye >> /dev/null
    # get new mails
    mbsync -qq -a
    # index new mails
    notmuch new --quiet
fi
