#!/usr/bin/env bash


# check if account is passed as argument
if [ "$#" -ne 1 ];
then
  echo "Usage: carta-deploy accountname"
  exit
fi

# check internet connection
is_connected || echo 'No connection'; exit 1

# get account name
ACCOUNT=$1

# get account data from password-store
PASS=$(pass email/${ACCOUNT})
USER=$(echo "$PASS" | sed '1d' | grep -w "^[Uu]ser" | \
  sed -e "s/^[Uu]ser[ \t]*:[ \t]*//" -e "s/[ \t]*$//")
FROM=$(echo "$PASS" | sed '1d' | grep -w "^[Ff]rom" | \
  sed -e "s/^[Ff]rom[ \t]*:[ \t]*//" -e "s/[ \t]*$//")

# define command line
MSMTP_CMD="msmtp"
MSMTP_OPTS=" -a ${ACCOUNT} --user ${USER} --from ${FROM} -t "

# send pipe stdin to smtp
cat /dev/stdin | ${MSMTP_CMD} ${MSMTP_OPTS}
